### ISSUE TITLE
Consider adapting a comprehensive toolkit like ms_toollib

### ISSUE THREAD

**Issue by eee555** [Alex1607/minesweeper-image#1]
ms_toollib is a comprehensive toolkit about minesweeper. if you need to read any video format, like .avf, .mvf, ..., I recommend it to you.

**Comment by eee555** [comment]
https://github.com/eee555/ms_toollib

**Comment by eee555** [comment]
custom format is redundant, in my opinion

**Comment by Alex1607** [comment]
Thank you! I will take a look at the library and see if it's a good fit.

**Comment by Alex1607** [comment]
Correct me if I am wrong @eee555, but this library from yours is for the solver algorithms, correct? I had to translate most of the stuff via a translator, so I might have some incorrect sentences. 
Also about the custom format, what format would you suggest? I am open to any other format which is able to achieve the same result as mine 😄

**Comment by eee555** [comment]
Not just the solver algorithms. What you need is to convert the video files into giFs, such as avf format of arbiter software. If you want to parse files in avf format using rust, ms_toollib is your best choice(or only choice). The current obstacle is that the documents are all written in Chinese. Ideally, there would also be instructions in English, which has not yet been achieved.

**Comment by eee555** [comment]
The test example of the parser is here.

https://github.com/eee555/ms_toollib/blob/main/base/tests/test_analyse.rs

Let me know any demo you need and I'll write it for you. I'll know how to improve my documentation.

**Comment by eee555** [comment]
AvfVideo_works

**Comment by eee555** [comment]
A similar repository is here

https://github.com/thefinerminer/minesweeper-rawvf

However, it is written in C and is not structured.

**Comment by eee555** [comment]
If you want to ask me what video format I recommend, I recommend evf format. Not just because I wrote it, because it's the only documented, unambiguous format. and it is actually used in my minesweeper software. 

however, I don't think you'll need it, because you only need to read the file, not generate it.

https://github.com/eee555/ms_toollib/blob/main/base/readme.md

**Comment by Alex1607** [comment]
Sorry for not responding for such a long time. 
But I think for now, at least, the format the project is currently using suits its use case better. Since the format you suggest seems really nice, but it's not as space efficient as I would like it to be.
